### ISSUE TITLE
Missing permissions when claiming role

### ISSUE THREAD

**Issue by LorenzCK** [circumspect/White-Rabbit#104]
Hello people,
first of all, thank you very much for your work. I have tried setting up the bot, using the Docker image, and so far I have been able to make it work. However, as soon as an user sends the `!claim <ROLE>` command, the bot prints out the following error:

```
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/whiterabbit/./src/players.py", line 44, in claim
    await ctx.author.add_roles(role)
  File "/usr/local/lib/python3.9/site-packages/discord/member.py", line 777, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/whiterabbit/./src/__main__.py", line 135, in on_command_error
    raise error
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

However, the bot was added to the server with Administrator permissions, so it should have all permissions needed.
Did anybody run into a similar problem? 😊

**Comment by circumspect** [comment]
Hi,
In the [Discord Developer Portal](https://discord.com/developers/applications), did you give the bot all of the privileged gateway intents?
![image](https://user-images.githubusercontent.com/40770208/177202057-713eb5da-fa90-4919-a864-e6baede9efb6.png)
