### ISSUE TITLE
No module named 'dotenv'

### ISSUE THREAD

**Issue by PealyOJ** [circumspect/White-Rabbit#119]
When running the py src command, I get an error that the dotenv module is not found:

C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2>py src
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2\src\__main__.py", line 10, in <module>
    from debug import DEBUG_COMMAND_LIST
  File "C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2\src\debug.py", line 7, in <module>
    import filepaths
  File "C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2\src\filepaths.py", line 1, in <module>
    import dirs
  File "C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2\src\dirs.py", line 4, in <module>
    from localization import DEFAULT_LOCALIZATION, LANGUAGE_KEY
  File "C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2\src\localization.py", line 4, in <module>
    import envvars
  File "C:\Users\[USER]\Documents\White Rabbit\White-Rabbit-0.12.2\src\envvars.py", line 4, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'

**Expected behavior**
Bot launches

**System Info**
OS: Windows 10
Python version: 3.11
Bot version: 0.12.2

**Other details**

**Comment by circumspect** [comment]
Hm, did you install the requirements? `requirements.txt` lists `python-dotenv` so Python \*should* be able to find the module

**Comment by PealyOJ** [comment]
> Hm, did you install the requirements? `requirements.txt` lists `python-dotenv` so Python *should* be able to find the module

Ahh, that was what was missing! Thanks.
I used the pip install command on python-dotenv
