### ISSUE TITLE
Bot is not reacting to commands

### ISSUE THREAD

**Issue by EikePeace** [circumspect/White-Rabbit#162]
**Description**
The bot is not reacting to any commands.

**Reproducing**
1. Set up bot and server according to documentation
2. Bot connects to server
3. join voice channel
4. enter "!init" command or any other

**Expected behavior**
The bot reacts and executes the appropriate command

**System Info**
OS: Windows 10
Python version: 3.11
Bot version: 0.15.1

I've tested this with 1 and 2 people in the "call" channel.
I don't know if at least 3 people are needed.

The same thing happened when the bot was setup via a docker installation.

**Comment by EikePeace** [comment]
Okay, it works with the 14.5

**Comment by EikePeace** [comment]
It is also working with the 15.0

So I think something in the 15.1 update broke it or changed something for the setup

**Comment by circumspect** [comment]
Hi,
Can you try deleting the `on_message` function in `__main__.py` and run it again? That seems to be the culprit, at least on my computer.

**Comment by WagagaCZ** [comment]
> Hi, Can you try deleting the `on_message` function in `__main__.py` and run it again? That seems to be the culprit, at least on my computer.

I have the same issue on 0.15.2 which is `on_message` free. I tried to reinstall requirements - no effect.
Python version is 3.11.3 (Tried on 3.11.2 as well)

Here is the console log:
```
[2023-04-28 10:25:46] [INFO    ] white-rabbit: Bot has logged in!
[2023-04-28 10:25:56] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.countapi.xyz', port=443): Max retries exceeded with url: /hit/white-rabbit-bot/commands-run (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\bot.py", line 1392, in process_commands
    await self.invoke(ctx)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\core.py", line 1015, in invoke
    await self.prepare(ctx)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\help.py", line 246, in prepare
    await super().prepare(ctx)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\core.py", line 934, in prepare
    await self.call_before_hooks(ctx)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\core.py", line 885, in call_before_hooks
    await hook(ctx)
  File "C:\WR\White-Rabbit\src\__main__.py", line 126, in before_invoke
    stats.increment_commands_run()
  File "C:\WR\White-Rabbit\src\stats.py", line 21, in increment_commands_run
    increment(COMMANDS_RUN)
  File "C:\WR\White-Rabbit\src\stats.py", line 10, in increment
    requests.get(API + counter)
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 518, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.countapi.xyz', port=443): Max retries exceeded with url: /hit/white-rabbit-bot/commands-run (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
```

**Comment by circumspect** [comment]
It seems like the service I was using to keep track of counters went offline for a bit, can you try it again? In the meantime I've pulled the release and will work on adding error handling in case it happens again.

**Comment by circumspect** [comment]
Actually, it looks like the API is still down. For now, I'd recommend just using 0.15.0.

**Comment by WagagaCZ** [comment]
> Hi, Can you try deleting the `on_message` function in `__main__.py` and run it again? That seems to be the culprit, at least on my computer.

And yes, it seems that was the problem. Before the API went down, bot reacted to commands fine!
