### ISSUE TITLE
Failed to import module

### ISSUE THREAD

**Issue by WagagaCZ** [circumspect/White-Rabbit#163]
**Description**
When starting the bot, program fails to import module "logging_tree"

**Reproducing**
Start the bot

**System Info**
OS: Win10
Python version: 3.11.2
Bot version: 0.15.2

**Other details**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\WR\White-Rabbit\src\__main__.py", line 12, in <module>
    import logging_tree
```

**Comment by circumspect** [comment]
Try rerunning `pip install -r requirements.txt` - this will install all the required modules.

**Comment by WagagaCZ** [comment]
Great, thanks for help.
Fixed
