### ISSUE TITLE
Error while issuing the python command

### ISSUE THREAD

**Issue by Gabbalo** [circumspect/White-Rabbit#85]
Hi everyone, 

I tried to install the bot and did well so far. Now, I issued the command "python src" while beeing in the White-Rabbit-Folder, according to the [Quickstart-Guide](https://white-rabbit.readthedocs.io/en/stable/user-guide/quickstart.html) The following wild error appeares and it is super effective.

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 153, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details()
  File "/usr/lib64/python2.7/runpy.py", line 125, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib64/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/hati/White-Rabbit/src/__main__.py", line 28
    async def on_ready():
        ^
```

Anyone knows, whats the problem is?

**Comment by circumspect** [comment]
Based on a quick glance, I think the problem is that python 2 doesn't support async. So you'll have to install a newer version

**Comment by Gabbalo** [comment]
python3
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```

python3.4

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 153, in _run_module_as_main
    mod_name, mod_spec, code = _get_main_module_details()
  File "/usr/lib64/python3.4/runpy.py", line 196, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib64/python3.4/runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "src/__main__.py", line 28
    async def on_ready():
        ^
SyntaxError: invalid syntax
```

python3.5

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_main_module_details(_Error)
  File "/usr/lib64/python3.5/runpy.py", line 219, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib64/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "src/__main__.py", line 91
    asyncio.create_task(bot_channel.send(f"{ctx.author.mention} " + LOCALIZATION_DATA["errors"]["CommandInWrongChannel"]))
                                                                ^
SyntaxError: invalid syntax
```

python3.6

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```

python3.7

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```

python3.8

```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```

python3.9

```
Traceback (most recent call last):
  File "/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hati/White-Rabbit/src/__main__.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```

Seems, that there are different errors in different Python versions. The breaking point was betweed 3.5 and 3.6
Anything else I might do to solve this? :/

**Comment by circumspect** [comment]
When you install a new version of python, you need to reinstall the libraries. Rerunning `pip install -r requirements.txt` should fix it

**Comment by circumspect** [comment]
And yeah, I think async was added around 3.6 so that makes sense

**Comment by Gabbalo** [comment]
I reinstalled the requirements für the different python versions. 
Python 3.6 trew another error after successful installation of the requirements

```
Loading localization data (en)... Done!
Traceback (most recent call last):
  File "src/utils.py", line 97, in get_image
    return find_url(localized_url, ImageResource.IMAGE_EXTENSIONS)
  File "src/utils.py", line 72, in find_url
    raise FileNotFoundError(url)
FileNotFoundError: https://raw.githubusercontent.com/circumspect/White-Rabbit/0.9.1/images/en/player-resources/Guide

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hati/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/debug.py", line 7, in <module>
    import filepaths
  File "src/filepaths.py", line 36, in <module>
    "guide": utils.get_image(PLAYER_RESOURCE_DIR, "Guide"),
  File "src/utils.py", line 103, in get_image
    fallback_url = f"{url}{'/'.join(fallback)}/{name}"
UnboundLocalError: local variable 'fallback' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 120, in <module>
    bot.load_extension(plugin)
  File "/home/hati/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/hati/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'debug' raised an error: UnboundLocalError: local variable 'fallback' referenced before assignment
```

I skipped everything in between and started this on python 3.9 and it seems it works now, sooooo the requirement should be somewhere in between :)

```
Loading localization data (en)... Done!
No dev_ids.txt found, making empty file
Logging in...
Bot has logged in!
```

Anyway: It works now, So i'll close the issue. Maybe you could consider to add the required python version in the installation guide.

**Comment by circumspect** [comment]
Will do, thanks! @all-contributors please add @Gabbalo for user testing
